manifest:
  remotes:
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: zmk
      remote: gpeye
      revision: main
      import: app/west.yml
    - name: zmk-periph-urchin
      remote: gpeye
      revision: main
  self:
    path: config
