manifest:
  remotes:
      # zmk official
    - name: zmkfirmwareforki
      url-base: https://github.com/GPeye
    - name: urob
      url-base: https://github.com/GPeye
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
  self:
    path: config